# Generated by Django 5.2.8 on 2026-01-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('starter', models.BooleanField(blank=True, null=True)),
                ('growth', models.BooleanField(blank=True, null=True)),
                ('scale', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='code',
            field=models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('scale', 'Scale')], default='starter', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='period',
            field=models.CharField(default='в месяц', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(default=list, help_text="['Feature 1', 'Feature 2']"),
        ),
    ]
