# Generated by Django 5.2.8 on 2025-11-23 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_url'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationsubscription',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['price']},
        ),
        migrations.RenameField(
            model_name='organizationsubscription',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='duration_months',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='duration_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organizationsubscription',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
