# Generated by Django 5.2.8 on 2026-01-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_planfeature_subscriptionplan_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='code',
            field=models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('scale', 'Scale')], default='starter', max_length=20),
        ),
    ]
