# Generated by Django 5.2.8 on 2026-01-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_alter_subscriptionplan_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='highlight',
            field=models.BooleanField(default=False),
        ),
    ]
