# Generated by Django 5.2.8 on 2026-01-20 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_subscriptionplan_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='period',
            field=models.DurationField(default=datetime.timedelta(days=30)),
        ),
    ]
