# Generated by Django 5.2.8 on 2026-01-27 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_products'),
        ('plans', '0007_alter_subscriptionplan_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsubscription',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='organizations.organization'),
        ),
    ]
