# Generated by Django 5.2.8 on 2026-01-30 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_alter_organizationsubscription_organization'),
        ('products', '0007_remove_product_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='products.product'),
        ),
    ]
