# Generated by Django 5.2.8 on 2026-01-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('badge', models.CharField(blank=True, max_length=50, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('hero_section', models.JSONField(blank=True, null=True)),
                ('features_section', models.JSONField(blank=True, null=True)),
                ('modules_section', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
