# Generated by Django 5.2.8 on 2026-01-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features_section_videoID',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hero_section_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
