# Generated by Django 5.2.8 on 2026-01-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_features_section_videoid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='features_section_videoID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
