# Generated by Django 5.2.8 on 2026-01-30 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_alter_organizationsubscription_organization'),
        ('products', '0005_product_demo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='plan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='plans.subscriptionplan'),
        ),
    ]
