# Generated by Django 5.2.8 on 2026-01-30 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='plan',
        ),
    ]
