# Generated by Django 6.0.3 on 2026-06-09 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Software Name')),
                ('version', models.CharField(max_length=50, verbose_name='Version')),
                ('install_path', models.CharField(max_length=500, verbose_name='Installation Path')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='products.product')),
            ],
            options={
                'verbose_name': 'Software Version',
                'verbose_name_plural': 'Software Versions',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'version')},
            },
        ),
    ]
