# Generated by Django 6.0.3 on 2026-05-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClickTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_trans_id', models.BigIntegerField(unique=True)),
                ('service_id', models.IntegerField()),
                ('merchant_trans_id', models.CharField(max_length=255)),
                ('merchant_prepare_id', models.BigIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('error', models.IntegerField(default=0)),
                ('error_note', models.CharField(blank=True, max_length=255)),
                ('organization_id', models.IntegerField(blank=True, null=True)),
                ('plan_id', models.IntegerField(blank=True, null=True)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Click Transaction',
                'verbose_name_plural': 'Click Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
