# Generated by Django 6.0.3 on 2026-05-16 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_pendingpayment'),
        ('plans', '0009_subscriptionplan_product'),
        ('products', '0007_remove_product_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingpayment',
            name='wallet_topup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pendingpayment',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='pendingpayment',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
