# Generated by Django 6.0.3 on 2026-06-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_pendingpayment_wallet_topup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingpayment',
            name='org_product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
