# Generated by Django 6.0.3 on 2026-06-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_create_wallets_for_existing_orgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Пополнение'), ('withdraw', 'Открытие базы')], max_length=10),
        ),
    ]
