# Generated by Django 5.2.8 on 2026-01-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_url'),
        ('products', '0004_alter_product_features_section_videoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='products.product'),
        ),
    ]
