# Generated by Django 5.2.8 on 2026-01-27 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_remove_organization_products_organizationproduct'),
        ('products', '0005_product_demo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationproduct',
            name='product_name',
        ),
        migrations.AddField(
            model_name='organizationproduct',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
    ]
