# Generated by Django 5.2.8 on 2026-01-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_remove_organizationproduct_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationproduct',
            name='product_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationproduct',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='organizationproduct',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
