# Generated by Django 5.2.8 on 2026-01-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_organizationproduct_product_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationproduct',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AddField(
            model_name='organizationproduct',
            name='chosen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationproduct',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
