# Generated by Django 5.2.8 on 2026-01-30 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_alter_organizationproduct_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='url',
        ),
    ]
