# Generated by Django 5.2.8 on 2026-01-30 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_organization_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationproduct',
            old_name='product_name',
            new_name='title',
        ),
    ]
