# Generated by Django 5.2.8 on 2026-02-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_rename_product_name_organizationproduct_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationproduct',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
