# Generated by Django 6.0.3 on 2026-06-09 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_organizationproduct_archive'),
        ('products', '0008_softwareversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationproduct',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_products', to='products.softwareversion'),
        ),
    ]
