# Generated by Django 6.0.3 on 2026-08-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_organization_oferta_promo_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='promo_code',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
    ]
