# Generated by Django 6.0.3 on 2026-08-17 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_alter_organization_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationproduct',
            name='user_count',
            field=models.PositiveIntegerField(default=1, help_text="Ushbu productga ulangan (tarifga kiruvchi + qo'shimcha) foydalanuvchilar soni"),
        ),
        migrations.CreateModel(
            name='OrganizationProductUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_1c', models.CharField(help_text='1C bazasidagi foydalanuvchi login/nomi', max_length=150)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text="False bo'lsa — organizatsiya tomonidan o'chirilgan (billingdan chiqarilgan)")),
                ('is_pending', models.BooleanField(default=False, help_text="Joriy oy davomida qo'shilgan, keyingi oydan billingga qo'shiladi")),
                ('activates_at', models.DateField(blank=True, help_text="Qaysi sanadan boshlab billingga qo'shiladi (keyingi oy boshi)", null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('organization_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_users', to='organizations.organizationproduct')),
            ],
            options={
                'verbose_name': 'Product foydalanuvchisi',
                'verbose_name_plural': 'Product foydalanuvchilari',
                'ordering': ['-added_at'],
                'unique_together': {('organization_product', 'login_1c')},
            },
        ),
    ]
