# Generated by Django 6.0.3 on 2026-08-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_organizationproduct_user_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationproduct',
            name='pending_user_count',
            field=models.PositiveIntegerField(blank=True, help_text="Joriy oy davomida so'ralgan yangi son — keyingi oy billingga qo'shiladi (bo'sh bo'lsa o'zgarish yo'q)", null=True),
        ),
        migrations.DeleteModel(
            name='OrganizationProductUser',
        ),
    ]
