# Generated by Django 6.0.3 on 2026-06-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
