# Generated by Django 6.0.3 on 2026-07-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_is_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender_contractor_inn',
            field=models.CharField(db_index=True, default=1212, max_length=14),
            preserve_default=False,
        ),
    ]
