# Generated by Django 6.0.3 on 2026-07-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_sender_contractor_inn'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender_contractor_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
