# Generated by Django 5.2.8 on 2025-11-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='organization_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
