# Generated by Django 5.2.8 on 2026-01-17 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_url'),
        ('users', '0003_customuser_organization_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='organization_url',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='organizations.organization'),
        ),
    ]
