# Generated by Django 5.2.8 on 2026-01-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_total_price_alter_order_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('free', 'Free')], default='pending', max_length=20),
        ),
    ]
